In [1]:
import pandas as pd
import import_ipynb
import climaticscoring as cs

 the total_gdp loss is 14021.5
the total loss caused by flood is 2260.3
the total loss caused by drought is 6986.4
the total loss caused by riverine flood is 1990.0
the total loss caused by flood is 2784.8
flood loss ratio w1 is 0.16
 drought loss ratio w2 is 0.5
riverrine flood loss w3 is 0.14
cyclone loss ratio w4 is 0.2

In [2]:
data = pd.read_csv('climate_risk.csv')
data

,Institution,agri_loan_pct,coastal_branches_pct,flood_zone_pct,energy_sector_pct
0,CRDB Bank,18.9,12.3,18.7,5.2
1,NBC Bank,25.0,22.1,25.4,3.8
2,NMB Bank,32.5,8.5,14.2,6.1
3,Stanbic Tanzania,15.0,18.4,12.1,9.7
4,Exim Bank,30.0,15.6,20.3,4.2
5,Azania Bank,35.0,5.2,28.9,2.1
6,DCB Bank,18.0,3.1,10.5,7.4
7,Mkombozi Bank,45.0,0.0,35.6,1.8
8,Akiba Commercial Bank,60.0,35.0,5.0,0.0
9,ABSA,45.0,20.0,15.0,20.0

In [3]:
print(cs.w1)

0.16

In [4]:
agri_w =cs.w1+cs.w2+cs.w3
cst_w=cs.w1+cs.w3+cs.w4
fld_w=cs.w1+cs.w3
en_w=cs.w2+cs.w1+cs.w3
total_w= cs.w1+cs.w2+cs.w3+cs.w4

In [5]:
def risk_tier(row):
    y =(row.agri_loan_pct*agri_w+row.coastal_branches_pct*cst_w+row.flood_zone_pct*fld_w+row.energy_sector_pct*en_w)/(total_w*100)
    if y >= 0.66:
        return f"High"
    elif y< 0.66 and y>= 0.34:
        return f"Medium"
    elif y<0.34 and y>=0:
        return f"Low"

data['Climate_risk_tier']=data[['agri_loan_pct','coastal_branches_pct','flood_zone_pct','energy_sector_pct']].apply(risk_tier, axis=1)

In [6]:
data

,Institution,agri_loan_pct,coastal_branches_pct,flood_zone_pct,energy_sector_pct,Climate_risk_tier
0,CRDB Bank,18.9,12.3,18.7,5.2,Low
1,NBC Bank,25.0,22.1,25.4,3.8,Medium
2,NMB Bank,32.5,8.5,14.2,6.1,Medium
3,Stanbic Tanzania,15.0,18.4,12.1,9.7,Low
4,Exim Bank,30.0,15.6,20.3,4.2,Medium
5,Azania Bank,35.0,5.2,28.9,2.1,Medium
6,DCB Bank,18.0,3.1,10.5,7.4,Low
7,Mkombozi Bank,45.0,0.0,35.6,1.8,Medium
8,Akiba Commercial Bank,60.0,35.0,5.0,0.0,High
9,ABSA,45.0,20.0,15.0,20.0,High

In [7]:
data.to_csv('climate_risk_tier.csv', index=False)